name: Release Apigee Agents

on:
  push:
    tags:
      - "*"
  workflow_call:

jobs:
  buildDiscoveryAgent:
    env:
      GOFLAGS: "-mod=mod"
      GOWORK: "off"
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/discovery
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build discovery agent
        working-directory: .
        run: |
          echo "would build and release the agent"

      - name: Upload release yaml
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.ACTION_SECRET }}
          file: traceability/apigee_traceability_agent.yml
          asset_name: apigee_traceability_agent.yml
          tag: ${{ github.ref }}
          overwrite: true
          body: "Apigee Traceability Agent YAML - ${{ github.ref }}"