name: Discovery Agent Docker

on:
  push:
    tags:
      - "*"

jobs:
  buildDiscoveryAgentDocker:
    env:
      GOFLAGS: "-mod=mod"
      GOWORK: "off"
      IMAGE_NAME: apigee_discovery_agent
      ORG_NAME: Axway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create commit_id & version files
        working-directory: .
        run: |
          echo "would build DA docker image"
