name: Build Apigee Discovery Agent

on:
  push:
    branches: [main, "*"]

jobs:
  buildDiscoveryAgent:
    env:
      GOFLAGS: "-mod=mod"
      GOWORK: "off"
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/discovery
    runs-on: ubuntu-latest
    steps:
      - name: Build discovery agent
        working-directory: .
        run: |
          echo "would build DA"

  call-workflow:
    uses: ./.github/workflows/apigee-agents-release.yml