name: Traceability Agent Docker

on:
  push:
    tags:
      - "*"

jobs:
  buildtraceabilityAgentDocker:
    env:
      GOFLAGS: "-mod=mod"
      GOWORK: "off"
      IMAGE_NAME: apigee_traceability_agent
      ORG_NAME: Axway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create commit_id & version files
        working-directory: traceability
        run: |
          echo "would build TA docker image"
