name: Build Apigee Traceability Agent

on:
  push:
    branches: [main, "*"]

jobs:
  buildTraceabilityAgent:
    env:
      GOFLAGS: "-mod=mod"
      GOWORK: "off"
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/traceability
    runs-on: ubuntu-latest
    steps:
      - name: Build traceability agent
        working-directory: .
        run: |
          echo "would build ta"
