name: TESTME

on: workflow_dispatch

jobs:
  doit:
    env:
      GOFLAGS: "-mod=mod"
      GOWORK: "off"
    defaults:
      run:
        working-directory: .
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Configure git
        run: |
          git config --global user.email "builder-lphxmjtnt11@axway.com"
          git config --global user.name "builder-lphxmjtnt11"
          git config --global push.followTags true

      - name: Get SDK version
        run: |
          export LATEST_REMOTE_TAG_CMD="git ls-remote --tags --refs --sort='version:refname' REMOTE_REPO | grep -Eo 'v?[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,3}$' | tail -1"
          REMOTE_REPO_PATH="https://github.com/Axway/agent-sdk"
          CMD=${LATEST_REMOTE_TAG_CMD/"REMOTE_REPO"/${REMOTE_REPO_PATH}}
          export SDK_VERSION=$(eval $CMD)
          echo "SDK version ${SDK_VERSION}"

      - name: Update SDK version
        working-directory: .
        run: |
          cat discovery/go.mod
          make dep-version sdk=v1.1.61
          cat discovery/go.mod

      - name: Push
        working-directory: .
        run: |
          git add -A
          git commit -m "INT - Update Dependencies"
          git push origin main
