name: TESTME

on: workflow_dispatch

jobs:
  doit:
    env:
      GOFLAGS: "-mod=mod"
      GOWORK: "off"
    defaults:
      run:
        working-directory: .
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      # - name: Configure git
      #   run: |
      #     git config --global user.email "builder-lphxmjtnt11@axway.com"
      #     git config --global user.name "builder-lphxmjtnt11"
      #     git config --global push.followTags true

      # - name: Create branch
      #   uses: peterjgrainger/action-create-branch@v2.4.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     branch: 'APIGOV-00000'

      - name: Get SDK version
        run: |
          export LATEST_REMOTE_TAG_CMD="git ls-remote --tags --refs --sort='version:refname' REMOTE_REPO | grep -Eo 'v?[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,3}$' | tail -1"
          REMOTE_REPO_PATH="https://github.com/Axway/agent-sdk"
          CMD=${LATEST_REMOTE_TAG_CMD/"REMOTE_REPO"/${REMOTE_REPO_PATH}}
          export SDK_VERSION=$(eval $CMD)
          echo "SDK version ${SDK_VERSION}"
          echo "SDK_VERSION=${SDK_VERSION}" >> $GITHUB_ENV
      - name: Update SDK version
        working-directory: .
        run: |
          cat discovery/go.mod
          echo "SDK_VERSION is ${SDK_VERSION}"
          echo "SDK_VERSION is ${{ env.SDK_VERSION }}"
          make dep-version sdk=v1.1.60
          cat discovery/go.mod

      # - name: Add and commit
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     author_email: builder-lphxmjtnt11@axway.com
      #     author_name: builder-lphxmjtnt11
      #     new_branch: APIGOV-00000
      #     message: 'Update to SDK ${SDK_VERSION}'
      #     push: true

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          # author: builder-lphxmjtnt11 <builder-lphxmjtnt11@axway.com>
          author: dfeldick <dfeldick@axway.com>
          committer: dfeldick <dfeldick@axway.com>
          branch: APIGOV-00000
          commit-message: 'Update to SDK ${{ env.SDK_VERSION }}'
          title: 'APIGOV-00000 - Update to SDK ${{ env.SDK_VERSION }}'
          delete-branch: true

      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          # token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}

      # - name: Configure git
      #   run: |
      #     git config --global user.email "dfeldick@axway.com"
      #     git config --global user.name "dfeldick"

      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
          # repo: juliangruber/approve-pull-request-action # optional          

      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
          method: squash
          # repo: juliangruber/octokit-action          