name: TESTME

on: workflow_dispatch

jobs:
  doit:
    env:
      GOFLAGS: "-mod=mod"
      GOWORK: "off"
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/discover
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Update SDK version
        working-directory: discovery
        run: |
          cat go.mod
          make dep-version sdk=v1.1.60 da=master
          cat go.mod
