# test  
name: Create tag for release

on:
  pull_request:
    types:
      - closed
  
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "I'm here"
        echo "head_ref ${{ github.head_ref }}"
        echo "ref_name ${{ github.ref_name }}"
        echo "ref ${{ github.ref }}"
        echo "base_ref ${{ github.base_ref }}"
  if_merged:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'APIGOV-UpdateSDK')
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
    - uses: actions/checkout@v3
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        echo "previous tag ${{ steps.tag_version.outputs.previous_tag }}
        echo "new tag ${{ steps.tag_version.outputs.new_tag }}
        git push origin ${{ github.ref_name }}
    
    # - name: Create a GitHub release
    #   uses: ncipollo/release-action@v1
    #   with:
    #     tag: ${{ steps.tag_version.outputs.new_tag }}
    #     name: Release ${{ steps.tag_version.outputs.new_tag }}
    #     body: ${{ steps.tag_version.outputs.changelog }}        

    call-workflow:
      uses: .github/workflows/apigee-agents-release.yml
