# this action is triggered by selecting the action in the github UI and then clicking "run workflow"
name: Update SDK version for release

on: workflow_dispatch

jobs:
  doit:
    env:
      GOFLAGS: "-mod=mod"
      GOWORK: "off"
    defaults:
      run:
        working-directory: .
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Get latest SDK version
        run: |
          export LATEST_REMOTE_TAG_CMD="git ls-remote --tags --refs --sort='version:refname' REMOTE_REPO | grep -Eo 'v?[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,3}$' | tail -1"
          REMOTE_REPO_PATH="https://github.com/Axway/agent-sdk"
          CMD=${LATEST_REMOTE_TAG_CMD/"REMOTE_REPO"/${REMOTE_REPO_PATH}}
          export SDK_VERSION=$(eval $CMD)
          echo "SDK_VERSION=${SDK_VERSION}" >> $GITHUB_ENV
      - name: Update SDK version in go.mod
        working-directory: .
        run: |
          echo "SDK_VERSION is ${{ env.SDK_VERSION }}"
          make dep-version sdk=v1.1.61
          cat discovery/go.mod

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          branch: APIGOV-UpdateSDK
          commit-message: 'Update to SDK ${{ env.SDK_VERSION }}'
          title: 'APIGOV-UpdateSDK - Update to SDK ${{ env.SDK_VERSION }}'
          delete-branch: true
          reviewers: dfeldick

      # Tried these, but never could get approval and auto merge to work. Keeping them here in case someone
      # wants to dig into it later.
      # - uses: peter-evans/enable-pull-request-automerge@v3
      #   with:
      #     pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}

      # - name: Approve Pull Request
      #   uses: juliangruber/approve-pull-request-action@v2
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     number: ${{ steps.cpr.outputs.pull-request-number }}
      #     # repo: juliangruber/approve-pull-request-action # optional          

      # - name: Merge Pull Request
      #   uses: juliangruber/merge-pull-request-action@v1
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     number: ${{ steps.cpr.outputs.pull-request-number }}
      #     method: squash
      #     # repo: juliangruber/octokit-action           

